packages:
  - "packages/*"
catalog:
  "@jsdevtools/version-bump-prompt": ^6.1.0
  "@types/node": 26.1.0
  commitlint: 21.2.0
  conventional-changelog-cli: ^5.0.0
  czg: 1.13.1
  eslint: 10.6.0
  glob: 13.0.6
  globals: 17.7.0
  husky: ^9.1.7
  prettier: 3.9.4
  prettier-plugin-tailwindcss: 0.8.0
  rolldown: 1.1.4
  rolldown-plugin-dts: 0.26.0
  tsup: ^8.5.1
  typescript: ^6.0.3

catalogMode: prefer

catalogs:
  commitlint:
    '@commitlint/cli': 21.2.0
    '@commitlint/config-conventional': 21.2.0
    '@commitlint/types': 21.2.0
    commitizen: 4.3.2
  eslint-dev:
    "@eslint-react/eslint-plugin": 5.10.0
    eslint-flat-config-utils: 3.2.0
    eslint-plugin-format: ^2.0.1
    eslint-plugin-prettier: 5.5.6
    eslint-plugin-react: ^7.37.5
    eslint-plugin-react-hooks: 7.1.1
    eslint-plugin-react-refresh: 0.5.3
    eslint-plugin-vue: 10.9.2
    eslint-typegen: ^2.3.1
    prettier-plugin-slidev: ^1.0.5
    tsx: 4.22.4
    vue-eslint-parser: 10.4.1

  eslint-prod:
    "@antfu/install-pkg": ^1.1.0
    "@clack/prompts": 1.6.0
    "@eslint-community/eslint-plugin-eslint-comments": 4.7.2
    '@stylistic/eslint-plugin': ^5.10.0
    "@typescript-eslint/eslint-plugin": 8.62.1
    "@typescript-eslint/parser": 8.62.1
    eslint-plugin-import-x: 4.17.1
    eslint-plugin-jsdoc: 63.0.10
    eslint-plugin-jsonc: 3.2.0
    eslint-plugin-markdown: ^5.1.0
    eslint-plugin-n: 18.2.1
    eslint-plugin-perfectionist: 5.9.1
    eslint-plugin-toml: 1.4.0
    eslint-plugin-yml: 3.5.0
    jsonc-eslint-parser: ^3.1.0
    local-pkg: 1.2.1
    toml-eslint-parser: ^1.0.3
    yaml-eslint-parser: ^2.0.0
